server:
  port: ${PORT:5003}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}
  redis:
    url: ${REDIS_URL}
    lettuce:
      pool:
        enabled: true
  jpa:
    show-sql: ${LOG_SQL:false}
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC
  flyway:
    enabled: false
logging:
  level:
    '[org.hibernate.type.descriptor.sql]': ${LOG_SQL_BIND_VARS:INFO}
management:
  endpoints:
    web:
      exposure:
        include: '*'
org:
  jobrunr:
    background-job-server:
      enabled: true
    database:
      skip-create: true
      table-prefix: scheduler