server:
  port: ${PORT:5000}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}
  redis:
    url: ${REDIS_URL}
  jpa:
    show-sql: ${LOG_SQL:false}
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC
  flyway:
    enabled: false
logging:
  level:
    '[org.hibernate.type.descriptor.sql]': ${LOG_SQL_BIND_VARS:INFO}
org:
  jobrunr:
    database:
      datasource: redis
aflstats:
  environment: ${APP_ENV:development}
  year: ${YEAR:2020}
